In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
data = pd.read_excel('/Users/shreyavora/Desktop/deliriumPaper/UCSFDelirium/demographics.xlsx')

#data = pd.read_excel('demogpraphics.xlsx', engine='openpyxl')
data = data.iloc[:128]

print(data.columns)

Index(['Master Record ID', 'Event Name',
       'Sequential Organ Failure Assessment (SOFA) Score', 'Age at Admission',
       'Sex at Birth', 'Race', 'Hispanic ethnicity',
       'Length of Hospitalization', 'ICU Length of Stay', 'SOFA', 'WHO Scale',
       'Remdesivir', 'Remdesivir Date Started (HD)',
       'Remdesiver date ended (HD)', 'Convalescent plasma',
       'Conv Plasma Date Started', 'Conv Plasma HD ended', 'IV steroids',
       'IV steroid HD started', 'IV steroid HD ended', 'Dex given',
       'Methylpred given', 'Hydrocort given', 'Dementia', 'Deceased',
       'Cause of death',
       'Was patient on ECMO at any point since the last study visit?',
       'Non-invasive ventilation (e.g. BiPAP, CPAP)  ',
       'Nasal cannula, face mask, or HFNC oxygen therapy',
       'Maximum O2 flow via NC or face mask', 'Invasive ventilation',
       'Delirium at any time during hospitalization'],
      dtype='object')

In [2]:
selected_columns = ['Age at Admission', 'Sex at Birth', 'Race', 'Hispanic ethnicity', "SOFA", "WHO Scale", 'Delirium at any time during hospitalization']
data = data[selected_columns]

data['Age at Admission'] = pd.to_numeric(data['Age at Admission'], errors='coerce')
average_age = data['Age at Admission'].mean()
data['Age at Admission'].fillna(average_age, inplace=True)
data['Age at Admission'] = np.ceil(data['Age at Admission']).astype(int)
#print(data.head())

#print(data['Age at Admission'].isna().sum())
#print(data['Sex at Birth'].isna().sum())
#print(data['Hispanic ethnicity'].isna().sum())
#print(data['SOFA'].isna().sum())

/var/folders/jz/c0wt1w7j7wz0wp1g3y6jcx0w0000gn/T/ipykernel_35267/2879664882.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age at Admission'].fillna(average_age, inplace=True)

In [3]:
#there is one empty 
average_SOFA = data['SOFA'].mean()
data['SOFA'].fillna(average_SOFA, inplace=True)
data['SOFA'] = np.ceil(data['SOFA']).astype(int)
print(data.head())
print(data['WHO Scale'].isna().sum())
average_WHO = data['WHO Scale'].mean()
data['WHO Scale'].fillna(average_WHO, inplace=True)
data['WHO Scale'] = np.ceil(data['WHO Scale']).astype(int)
#print(data.head())
print(data['WHO Scale'].isna().sum())

   Age at Admission Sex at Birth                                      Race  \
0                35       Female                                     White
1                44       Female                    Other / Multiple Races
2                84         Male  Native Hawaiian / Other Pacific Islander
3                67         Male                                     White
4                51       Female                  Black / African American

  Hispanic ethnicity  SOFA  WHO Scale  \
0                  0    10        7.0
1                  0     4        5.0
2                  0     0        3.0
3                  0     9        7.0
4                  0    10        7.0

   Delirium at any time during hospitalization
0                                          1.0
1                                          0.0
2                                          1.0
3                                          0.0
4                                          0.0
1
0

/var/folders/jz/c0wt1w7j7wz0wp1g3y6jcx0w0000gn/T/ipykernel_35267/3480717273.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['SOFA'].fillna(average_SOFA, inplace=True)
/var/folders/jz/c0wt1w7j7wz0wp1g3y6jcx0w0000gn/T/ipykernel_35267/3480717273.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['SOFA'].fillna(average_SOFA, inplace=True)
/var/folders/jz/c0wt1w7j7wz0wp1g3y6jcx0w0000gn/T/ipykernel_35267/3480717273.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['WHO Scale'].fillna(average_WHO, inplace=True)

In [4]:
data['Sex at Birth'] = data['Sex at Birth'].map({'Male': 0, 'Female': 1})
# Remove any leading or trailing spaces in the column (if any)
data['Hispanic ethnicity'] = data['Hispanic ethnicity'].str.strip()
# Check for any non-numeric or unexpected values in the column
print(data['Hispanic ethnicity'].unique())
# Convert the column to numeric, coercing non-numeric values to NaN
data['Hispanic ethnicity'] = pd.to_numeric(data['Hispanic ethnicity'], errors='coerce')
# If there are NaN values after conversion, fill them with 0
data['Hispanic ethnicity'].fillna(0, inplace=True)
print(data[['Age at Admission', 'Sex at Birth', 'Hispanic ethnicity']].dtypes)
print(data['Hispanic ethnicity'].unique())

[nan 'unknown']
Age at Admission        int64
Sex at Birth            int64
Hispanic ethnicity    float64
dtype: object
[0.]

/var/folders/jz/c0wt1w7j7wz0wp1g3y6jcx0w0000gn/T/ipykernel_35267/3524041683.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Hispanic ethnicity'].fillna(0, inplace=True)

In [5]:
data.head()

,Age at Admission,Sex at Birth,Race,Hispanic ethnicity,SOFA,WHO Scale,Delirium at any time during hospitalization
0,35,1,White,0.0,10,7,1.0
1,44,1,Other / Multiple Races,0.0,4,5,0.0
2,84,0,Native Hawaiian / Other Pacific Islander,0.0,0,3,1.0
3,67,0,White,0.0,9,7,0.0
4,51,1,Black / African American,0.0,10,7,0.0

In [6]:
from sklearn.preprocessing import OneHotEncoder

unique_values = data['Race'].unique()
print (len(unique_values))

ohe = OneHotEncoder(handle_unknown="ignore", sparse_output = False).set_output(transform = "pandas")
ohetransform = ohe.fit_transform(data[['Race']])
ohetransform
data = pd.concat([data, ohetransform], axis = 1).drop(columns= ["Race"])
data.head()
print(data.head)
print(len(data.columns))
data.to_csv('Demo_data.csv', index=False, header=True, sep=',')


print(data.columns)

7
<bound method NDFrame.head of      Age at Admission  Sex at Birth  Hispanic ethnicity  SOFA  WHO Scale  \
0                  35             1                 0.0    10          7
1                  44             1                 0.0     4          5
2                  84             0                 0.0     0          3
3                  67             0                 0.0     9          7
4                  51             1                 0.0    10          7
..                ...           ...                 ...   ...        ...
123                55             0                 0.0     0          4
124                69             0                 0.0     1          5
125                67             0                 0.0    10          7
126                51             0                 0.0     6          5
127                50             1                 0.0    10          7

     Delirium at any time during hospitalization  \
0                                            1.0
1                                            0.0
2                                            1.0
3                                            0.0
4                                            0.0
..                                           ...
123                                          0.0
124                                          1.0
125                                          0.0
126                                          0.0
127                                          1.0

     Race_American Indian / Alaska Native  Race_Asian  \
0                                     0.0         0.0
1                                     0.0         0.0
2                                     0.0         0.0
3                                     0.0         0.0
4                                     0.0         0.0
..                                    ...         ...
123                                   0.0         0.0
124                                   0.0         0.0
125                                   0.0         0.0
126                                   0.0         0.0
127                                   0.0         0.0

     Race_Black / African American  \
0                              0.0
1                              0.0
2                              0.0
3                              0.0
4                              1.0
..                             ...
123                            0.0
124                            0.0
125                            0.0
126                            1.0
127                            1.0

     Race_Native Hawaiian / Other Pacific Islander  \
0                                              0.0
1                                              0.0
2                                              1.0
3                                              0.0
4                                              0.0
..                                             ...
123                                            0.0
124                                            0.0
125                                            0.0
126                                            0.0
127                                            0.0

     Race_Other / Multiple Races  Race_Unknown  Race_White
0                            0.0           0.0         1.0
1                            1.0           0.0         0.0
2                            0.0           0.0         0.0
3                            0.0           0.0         1.0
4                            0.0           0.0         0.0
..                           ...           ...         ...
123                          1.0           0.0         0.0
124                          1.0           0.0         0.0
125                          0.0           0.0         1.0
126                          0.0           0.0         0.0
127                          0.0           0.0         0.0

[128 rows x 13 columns]>
13
Index(['Age at Admission', 'Sex at Birth', 'Hispanic ethnicity', 'SOFA',
       'WHO Scale', 'Delirium at any time during hospitalization',
       'Race_American Indian / Alaska Native', 'Race_Asian',
       'Race_Black / African American',
       'Race_Native Hawaiian / Other Pacific Islander',
       'Race_Other / Multiple Races', 'Race_Unknown', 'Race_White'],
      dtype='object')

In [7]:
data.head()

,Age at Admission,Sex at Birth,Hispanic ethnicity,SOFA,WHO Scale,Delirium at any time during hospitalization,Race_American Indian / Alaska Native,Race_Asian,Race_Black / African American,Race_Native Hawaiian / Other Pacific Islander,Race_Other / Multiple Races,Race_Unknown,Race_White
0,35,1,0.0,10,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,44,1,0.0,4,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,84,0,0.0,0,3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,67,0,0.0,9,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,51,1,0.0,10,7,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [8]:
# Oversample and plot imbalanced dataset with SMOTE
from collections import Counter
#from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE
from matplotlib import pyplot
from numpy import where
# define dataset
#X, y = make_classification(n_samples=10000, n_features=2, n_redundant=0,
#	n_clusters_per_class=1, weights=[0.99], flip_y=0, random_state=1)
# summarize class distribution
# transform the dataset
oversample = SMOTE()
X = data.drop(columns=['Delirium at any time during hospitalization'], inplace=False)
y = data['Delirium at any time during hospitalization']
counter = Counter(y)
print(counter)
X.head()

Counter({0.0: 97, 1.0: 31})

,Age at Admission,Sex at Birth,Hispanic ethnicity,SOFA,WHO Scale,Race_American Indian / Alaska Native,Race_Asian,Race_Black / African American,Race_Native Hawaiian / Other Pacific Islander,Race_Other / Multiple Races,Race_Unknown,Race_White
0,35,1,0.0,10,7,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,44,1,0.0,4,5,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,84,0,0.0,0,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,67,0,0.0,9,7,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,51,1,0.0,10,7,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [9]:
X, y = oversample.fit_resample(X, y)
# summarize the new class distribution
# scatter plot of examples by class label
X.shape

(194, 12)

In [10]:
counter = Counter(y)
print(counter)

Counter({1.0: 97, 0.0: 97})

In [11]:
import pandas as pd

# Assuming X is a DataFrame and y is a Series or array
X_resampled = pd.DataFrame(X)
y_resampled = pd.Series(y, name='target')

# Concatenate X and y
df_resampled = pd.concat([X_resampled, y_resampled], axis=1)

# Save to CSV
df_resampled.to_csv('oversampled_data.csv', index=False)